### PR TITLE
Home page, toggling, and form

### PR DESCRIPTION
**Pull request by sdtrachsel**
Added home page content
Added page toggling to nav buttons
Added the form for adding a trip.

### CODE REVIEW

**Comment by sdtrachsel** [comment]
@CBradsen

**Review by CBradsen — COMMENTED** [review]
Sharie, wow! You've come out of the gate blazing! 
You've already written so much clean code and som many reusable functions. 
You've even made consideration for time as it passes to check which trips are future and past as new ones are made and time goes on. 
And you have a function to account for US currency. 

It looks like you are planning to show the upcoming trips and have buttons for viewing the past and for making a new trip. Am I reading this right? 

Are the destination cards going to be something that includes the photos?

Love how simple and easy to read your function names are. 
It lets someone new to the code really understand what's happening. 

And I liked how clean and reusable your code is. Like here: 
function populatePastPage() {
    createTripsTable(pastTripTable, currentUserTrips.findByTense('past'))
}
function populatePlanTripPage() {
    createDestinationCards(allDestinations.allDestinations)
}

Keep rocking on!

**Comment by sdtrachsel** [comment]
@nicktu12

**Comment by nicktu12** [comment]
👍🏻

**Pull request merged**
